#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.


# prevent automatically setup the assets
cd $OPENSHIFT_REPO_DIR
if [ -f Gemfile ]
  then
    echo ----------------------------[ Cheating: rename Gemfile in order to skip asset procompilation ]
    cd $OPENSHIFT_REPO_DIR
    mv Gemfile Gemfile.hidden
  else
    echo ----------------------------[ Not cheating: Gemfile not found ]
fi