development:
  adapter: postgresql
  encoding: utf8
  database: owenwj
  host: localhost
  pool: 5
  username: owenwj
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: owenwj
  host: localhost
  pool: 5
  username: owenwj
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: owenwj
  host: localhost
  pool: 5
  username: owenwj
  password:

cucumber:
  <<: *TEST