development:
  adapter: postgresql
  encoding: utf8
  database: yanyee
  host: localhost
  pool: 5
  username: yanyee
  password: 123456

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: yanyee
  host: localhost
  pool: 5
  username: yanyee
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  database: yanyee
  host: localhost
  pool: 5
  username: yanyee
  password: 123456

cucumber:
  <<: *TEST