development:
  adapter: postgresql
  encoding: utf8
  database: JoyCorn
  host: localhost
  pool: 5
  username: owenwj
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: JoyCorn
  host: localhost
  pool: 5
  username: owenwj
  password:

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>